steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/sandbox-tlengyel/products-api:$SHORT_SHA'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/sandbox-tlengyel/products-api:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  args:
  - 'beta'
  - 'run'
  - 'deploy'
  - 'products-api'
  - '--image'
  - 'gcr.io/sandbox-tlengyel/products-api:$SHORT_SHA'
  - '--region'
  - 'us-central1'

 gcloud beta run deploy --image gcr.io/$PROJECT/helloworld --region us-central1