swagger: '2.0'
info:
  version: "2.0.0"
  title: Products API
  description: Sample API for SU products add and get.
security: 
  - APIKeyQueryParam: []
produces:
  - application/json
x-google-backend:
  address: https://helloworld-un6nz7ltbq-uc.a.run.app
host: "helloworld-un6nz7ltbq-uc.a.run.app"

paths:
  /products:
    get:
      summary: return list of products
      operationId: products.get
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
    post:
      summary: return product new id 
      description: add product to db
      operationId: products.post
      parameters:
        - in: body
          name: product
          required: true
          description: required fields for products
          schema:
            $ref: '#/definitions/Product'
      responses:
        200:
          description: OK
          schema:
            type: string
  /product/{product_id}:
    get:
      summary: specific product access
      description: return specific product from db
      operationId: product.get
      parameters: 
        - in: path
          name: product_id
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Product'
securityDefinitions:
  APIKeyQueryParam:
    type: apiKey
    name: api_key
    in: query
    
definitions:
  Product:
    properties:
      id:
        type: integer
      title:
        type: string
      price:
        type: number
        format: float
    required:
      - id
      - title
      - price
schemes:
 - https
